name: Sheet to Json Workflow

on:
  schedule:
    # every 20 minutes the job will run
    - cron: "*/20 * * * *"
  push:
    branches:
      - main

jobs:
  update-json-data:
    runs-on: ubuntu-20.04
    timeout-minutes: 19

    steps:
      - name: Set Timezone to IST
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Kolkata"
      - uses: actions/checkout@v2
      - run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm install

      - name: push
        run: |
          bash ./main.sh 2>> /tmp/apidata_err
          echo "the job completed"
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          RESOURCES_SHEET_ID: ${{ secrets.RESOURCES_SHEET_ID }}
          SHEET_LOCALE: ${{ secrets.SHEET_LOCALE }}
          STUCK_BOT: ${{ secrets.STUCK_BOT }}
      - name: show job status
        if: always()
        run: |
          git checkout main
          node lib/notify_tg.js $status
        env:
          status: ${{job.status}}
          STUCK_BOT: ${{ secrets.STUCK_BOT }}
          GITHUB_TOKEN: ${{ secrets.github_token }}
